{% set name = "coinbase-advanced-py" %}
{% set version = "1.8.4" %}
{% set python_min = 3.8 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coinbase/coinbase-advanced-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e38401e7a2e76065d83a4f9bf33ed5fbf029375746ffe4d35a9f6c83d5181b8d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - requests >=2.31.0
    - setuptools
  run:
    - backoff >=2.2.1
    - cryptography >=42.0.0
    - PyJWT >=2.8.0
    - websockets >=12.0,<14
    - python >={{ python_min }}

test:
  imports:
    - coinbase
  source_files:
    - tests
  requires:
    - requests-mock==1.11.0
    - asynctest==0.13.0
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -m unittest discover -v

about:
  home: https://github.com/coinbase/coinbase-advanced-py
  summary: 'Coinbase Advanced API Python SDK'
  description: |
    Welcome to the official Coinbase Advanced API Python SDK. This python project was
    created to allow coders to easily plug into the Coinbase Advanced API. This SDK
    also supports easy connection to the Coinbase Advanced Trade WebSocket API.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://docs.cloud.coinbase.com/advanced-trade-api/docs/sdk-overview
  dev_url: https://coinbase.github.io/coinbase-advanced-py/

extra:
  recipe-maintainers:
    - MementoRC
