{% set name = "coinbase-advanced-py" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coinbase/coinbase-advanced-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bd878be8e4cd82af91500ecd0b75f52785b576a9be68a9f784269a057ea285b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - requests >=2.31.0
    - setuptools
  run:
    - backoff >=2.2.1
    - cryptography >=42.0.0
    - PyJWT >=2.8.0
    - websockets >=12.0
    - python >=3.8

test:
  imports:
    - coinbase
  source_files:
    - tests
  requires:
    - requests-mock==1.11.0
    - asynctest==0.13.0
    - pip
  commands:
    - pip check
    - python -m unittest discover -v

about:
  home: https://github.com/coinbase/coinbase-advanced-py
  summary: 'Coinbase Advanced API Python SDK'
  description: |
    Welcome to the official Coinbase Advanced API Python SDK. This python project was
    created to allow coders to easily plug into the Coinbase Advanced API. This SDK
    also supports easy connection to the Coinbase Advanced Trade WebSocket API.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://docs.cloud.coinbase.com/advanced-trade-api/docs/sdk-overview
  dev_url: https://coinbase.github.io/coinbase-advanced-py/

extra:
  recipe-maintainers:
    - MementoRC
