{% set name = "coinbase-advanced-py" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coinbase/coinbase-advanced-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8fe62717eb52c9e5e9e5321bb06b5cffa1c924165c7180677bec8c71bf12b3c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - requests >=2.31.0
    - setuptools
  run:
    - backoff >=2.2.1
    - cryptography >=42.0.0
    - PyJWT >=2.8.0
    - websockets >=12.0
    - python >=3.8

test:
  imports:
    - coinbase
  source_files:
    - tests
  requires:
    - requests-mock==1.11.0
    - asynctest==0.13.0
    - pip
  commands:
    - pip check
    - python -m unittest discover -v

about:
  home: https://github.com/coinbase/coinbase-advanced-py
  summary: 'Coinbase Advanced API Python SDK'
  description: |
    Welcome to the official Coinbase Advanced API Python SDK. This python project was
    created to allow coders to easily plug into the Coinbase Advanced API. This SDK
    also supports easy connection to the Coinbase Advanced Trade WebSocket API.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://docs.cloud.coinbase.com/advanced-trade-api/docs/sdk-overview
  dev_url: https://coinbase.github.io/coinbase-advanced-py/

extra:
  recipe-maintainers:
    - MementoRC
